spring:
  flyway:
    validate-on-migrate: false

scheduler:
  measurement-collection: 0/15 * * * * *

terminal:
  users:
    - login: dr
      password-sha256: 'dr' # todo
      roles:
        - ADMIN