spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pv_test
    username: root
    password: root
  resources:
    static-locations: df
  jpa:
    open-in-view: false

scheduler:
  daily-summary: 0 1 0 * * *

terminal:
  users:
    - login: admin
      password-sha256: ${ADMIN_PASSWORD_SHA256}
      roles:
        - ROLE_ADMIN

feign:
  httpclient:
    disable-ssl-validation: true
    enabled: false
  okhttp:
    enabled: true