spring:
  flyway:
    validate-on-migrate: false
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

scheduler:
  daily-summary: 0 0/5 * * * *

terminal:
  users:
    - login: dr
      password-sha256: 'dr' # todo
      roles:
        - ROLE_ADMIN