image: openjdk:8-jdk-slim

stages:
  - build
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew test
  except:
    - tags

build release:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew test bootWar
  artifacts:
    name: "pv-stats-$CI_COMMIT_TAG"
    paths:
      - pv-stats/build/libs/*.war
    expire_in: 30 days
  only:
    - tags

docker:
  stage: publish
  script:
    - chmod +x gradlew
    - >-
      ./gradlew jib
      -Djib.to.auth.username=$CI_REGISTRY_USER
      -Djib.to.auth.password=$CI_REGISTRY_PASSWORD
      -Djib.console=plain
  only:
    - tags