version: "3.7"
services:
  mariadb:
    image: mariadb:10.5.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./resources/maria-init:/docker-entrypoint-initdb.d:z
      - ./resources/maria-data:/var/lib/mysql:z
    restart: on-failure
    networks:
      - sh-network
  pv-stats:
    image: pv-stats:${PV_STATS_VERSION}
    container_name: pv-stats
    environment:
      PV_STATS_DB_USER: ${PV_STATS_DB_USER}
      PV_STATS_DB_PASSWORD: ${PV_STATS_DB_PASSWORD}
      PV_STATS_JAVA_OPTS: ${PV_STATS_JAVA_OPTS}
      ADMIN_PASSWORD_SHA256: ${PV_STATS_ADMIN_PASSWORD_SHA256}
    ports:
      - 8080:8080
    volumes:
      - ./config/pv-stats:/app/config:z
      - ./logs/pv-stats:/app/logs:z
    networks:
      - sh-network
networks:
  sh-network:
    driver: bridge