version: "3.7"
services:
  mariadb:
    image: mariadb:10.5.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./resources/maria-init:/docker-entrypoint-initdb.d:z
      - ./resources/maria-data:/var/lib/mysql:z
    restart: on-failure
    networks:
      - sh-network
  pv-stats:
    image: pv-stats:${PV_STATS_VERSION}
    container_name: pv-stats
    environment:
      PV_STATS_DB_USER: ${PV_STATS_DB_USER}
      PV_STATS_DB_PASSWORD: ${PV_STATS_DB_PASSWORD}
      PV_STATS_JAVA_OPTS: ${PV_STATS_JAVA_OPTS}
      ADMIN_PASSWORD_SHA256: ${PV_STATS_ADMIN_PASSWORD_SHA256}
    volumes:
      - ./config/pv-stats:/app/config:z
      - ./logs/pv-stats:/app/logs:z
    networks:
      - sh-network
    depends_on:
      - mariadb
  # https://grafana.com/docs/grafana/latest/installation/configuration/
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    restart: on-failure
    environment:
      GF_INSTALL_PLUGINS: simpod-json-datasource 0.1.7
    volumes:
      - ./resources/grafana-data:/var/lib/grafana:z
    networks:
      - sh-network
  httpd:
    image: httpd:2.4
    container_name: httpd
    entrypoint: /httpd/resources/entrypoint.sh
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/httpd:/usr/local/apache2/conf/pv-stats:z
      - ./resources/httpd:/httpd/resources:z
      - ${PV_CERT_FILE}:/httpd/ssl_cert
      - ${PV_KEY_FILE}:/httpd/ssl_key
      - ${PV_FULLCHAIN_FILE}:/httpd/ssl_fullchain
    networks:
      - sh-network
networks:
  sh-network:
    driver: bridge